# Generated by Django 3.1.6 on 2021-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_auto_20210806_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='zonename',
            field=models.CharField(max_length=20),
        ),
    ]
