# Generated by Django 3.1.6 on 2021-09-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_auto_20210810_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyiaq',
            name='battery',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
