# Generated by Django 3.1.6 on 2022-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_dailyiaq_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MACID', models.CharField(max_length=20)),
                ('Temp', models.FloatField()),
                ('Humi', models.FloatField()),
                ('Co2', models.FloatField()),
                ('PM1', models.FloatField()),
                ('PM2', models.FloatField()),
                ('PM4', models.FloatField()),
                ('PM10', models.FloatField()),
                ('NC0', models.FloatField()),
                ('NC1', models.FloatField()),
                ('NC2', models.FloatField()),
                ('NC4', models.FloatField()),
                ('NC10', models.FloatField()),
                ('PtSize', models.FloatField()),
                ('O2', models.FloatField()),
                ('VOC', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
