# Generated by Django 4.0.1 on 2022-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_multisensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturehumidity',
            name='x1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehumidity',
            name='x2',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehumidity',
            name='y1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehumidity',
            name='y2',
            field=models.FloatField(default=None, null=True),
        ),
    ]
