# Generated by Django 4.0.1 on 2022-11-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20210722_1249'),
        ('sensor', '0008_alter_temperaturehumidity_x1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSensorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MACID', models.CharField(max_length=20)),
                ('Temp', models.FloatField()),
                ('Humi', models.FloatField()),
                ('Co2', models.FloatField()),
                ('PM1', models.FloatField()),
                ('PM2', models.FloatField()),
                ('PM4', models.FloatField()),
                ('PM10', models.FloatField()),
                ('NC0', models.FloatField()),
                ('NC1', models.FloatField()),
                ('NC2', models.FloatField()),
                ('NC4', models.FloatField()),
                ('NC10', models.FloatField()),
                ('PtSize', models.FloatField()),
                ('O2', models.FloatField()),
                ('VOC', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.mastergateway')),
            ],
        ),
    ]
