# Generated by Django 4.0.1 on 2022-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(default=None, max_length=100)),
                ('reading', models.FloatField(default=0.0, null=True)),
                ('distancelader', models.FloatField(default=0.0, null=True)),
                ('dcstatus', models.IntegerField(default=0, null=True)),
                ('battery', models.FloatField(default=0.0, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(default=None, max_length=100)),
                ('reading', models.FloatField(default=0.0, null=True)),
                ('distancelader', models.FloatField(default=0.0, null=True)),
                ('dcstatus', models.IntegerField(default=0, null=True)),
                ('battery', models.FloatField(default=0.0, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
