# Generated by Django 3.1.6 on 2023-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightscale', '0004_sensors_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='display',
            field=models.FloatField(default=0, null=True),
        ),
    ]
