# Generated by Django 3.1.6 on 2022-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('battery', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('vehicleid', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=50)),
                ('lastseen', models.DateTimeField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
