# Generated by Django 4.0.1 on 2022-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('gateway', models.CharField(max_length=50)),
                ('lastseen', models.DateTimeField()),
            ],
        ),
    ]
