# Generated by Django 4.0.1 on 2022-02-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210805_1151'),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeregistration'),
        ),
    ]
