# Generated by Django 4.0.1 on 2022-02-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_floormap_image'),
        ('alert', '0002_alter_alert_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='floor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.floormap'),
        ),
    ]
