# Generated by Django 4.0.1 on 2022-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='lastseen',
            field=models.DateTimeField(default=None),
        ),
    ]
