# Generated by Django 4.0.1 on 2022-11-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energytracking',
            old_name='power',
            new_name='energy',
        ),
    ]
