# Generated by Django 4.0.1 on 2022-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_rename_power_energytracking_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytracking',
            name='powerFactor',
            field=models.FloatField(default=0, null=True),
        ),
    ]
