# Generated by Django 4.0.1 on 2022-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employeeregistration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='battery',
            field=models.FloatField(default=None, null=True),
        ),
    ]
