# Generated by Django 4.0.1 on 2022-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employeeregistration_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='y',
            field=models.FloatField(default=None, null=True),
        ),
    ]
