# Generated by Django 4.0.1 on 2022-02-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_floormap_image'),
        ('employee', '0010_alter_employeeregistration_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(default=None, max_length=200)),
                ('tagid', models.CharField(default=None, max_length=20, unique=True)),
                ('battery', models.FloatField(default=None, null=True)),
                ('x', models.FloatField(default=None, null=True)),
                ('y', models.FloatField(default=None, null=True)),
                ('intime', models.DateTimeField(auto_now_add=True)),
                ('lastseen', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.floormap')),
            ],
        ),
    ]
