# Generated by Django 4.0.1 on 2022-02-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='roll',
            new_name='role',
        ),
    ]
