# Generated by Django 4.0.1 on 2022-02-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_rename_roll_file_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeregistration',
            old_name='roll',
            new_name='role',
        ),
    ]
