# Generated by Django 4.0.1 on 2022-02-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_rename_roll_employeeregistration_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
