# Generated by Django 4.0.1 on 2022-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='lastseen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
