# Generated by Django 4.0.1 on 2022-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employeeregistration_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='email',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='empid',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='phoneno',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
