# Generated by Django 4.0.1 on 2022-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employeeregistration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
