# Generated by Django 4.0.1 on 2022-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_employeeregistration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='x',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='y',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
