# Generated by Django 3.1.6 on 2022-12-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_floormap_image'),
        ('employee', '0018_alter_employeeregistration_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0, null=True)),
                ('y', models.FloatField(default=0.0, null=True)),
                ('battery', models.FloatField(default=None, null=True)),
                ('lastseen', models.DateTimeField(auto_now_add=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeeregistration')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.floormap')),
            ],
        ),
    ]
